# Generated by Django 4.2.2 on 2023-06-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Язык клиента'),
        ),
    ]
