# Generated by Django 4.2.2 on 2023-06-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_user_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
